### ISSUE TITLE
In the example app button 1 on the left hand side cannot be selected

### ISSUE THREAD

**Issue by danieljfarrell** [erndev/EDSidebar#5]
This is from the latest source, simply open the xcode project, build and run, and for some reason I can never select the first button on the left hand side.

I put a break point in buttonClicked:. When you click on button 1 it gets called twice, the first time with the correct index (0) then the second time the index is set to 1?

**Comment by unixo** [comment]
In `awakeFromNib` at line 56 you can find another small feature introduced by a branch merge, i.e. you can set a specific target/action for each button, instead of a method called for them all.
For button at index 0, the method `logThis` is called and, from within, next button is selected.
It's not a bug, only a way to demonstrate some features :)

**Comment by danieljfarrell** [comment]
Ah got you! That's actually really useful. Thank you.

**Comment by dbainbridge** [comment]
This caused too much confusion for me, especially since I did not check the "issues" here first.  It really looked like a bug to me at first.  You can show off this feature without the selectNext method call since it is already logging a message.
